require_relative '../book'
require_relative '../person'
require_relative '../student'
require_relative '../teacher'
require_relative '../classroom'
require_relative '../rental'
require_relative '../nameable'
require_relative '../decorator'
require_relative '../capitalize_decorator'
require_relative '../trimmer_decorator'

require 'yaml'